import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "김기태 & 박기영 결혼합니다",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <head>
        {/* <title>김기태 & 박기영 결혼합니다</title> */}
        <meta name="color-scheme" content="light" />
        <meta name="theme-color" content="#000000" />
        <meta property="og:title" content="김기태 & 박기영 결혼합니다." />
        <meta property="og:image" content="https://img.freepik.com/free-photo/groom-putting-ring-bride-s-finger_1157-338.jpg" />
        <meta property="og:description" content="10월 19일 11시 30분 플로렌스 오목교점" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
